version: "3"
services:
  auth:
    build: .
    ports:
      - 8083:8083
    environment:
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_SERVER_BASEURL: http://auth:8083
    depends_on:
      - etcd

  users:
    image: tomisebjanic/rso-users:0.9.1
    ports:
      - 8082:8082
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres-users:5432/rsouser
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_SERVER_BASEURL: http://users:8082
    depends_on:
      - postgres-users
      - etcd
  postgres-users:
    image: postgres:10.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rsouser

  etcd:
    image: elcolio/etcd:2.0.10
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001
      - 7001:7001
  etcd-browser:
    image: buddho/etcd-browser
    ports:
      - 8000:8000
    environment:
      ETCD_HOST: http://etcd
      AUTH_PASS: doe
    depends_on:
      - etcd
