version: "3"
services:
  auth:
    build: .
    ports:
      - 8083:8083
    environment:
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
      KUMULUZEE_SERVER_BASEURL: http://auth:8083
    depends_on:
      - etcd

  etcd:
    image: elcolio/etcd:2.0.10
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001
      - 7001:7001
  etcd-browser:
    image: buddho/etcd-browser
    ports:
      - 8000:8000
    environment:
      ETCD_HOST: http://etcd
      AUTH_PASS: doe
    depends_on:
      - etcd
