kumuluzee:
  name: auth
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    ttl: 20
    ping-interval: 15
    etcd:
      hosts: http://localhost:2379
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      disk-space-health-check:
        threshold: 100000000
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    webinstrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
      - name: authEndpoint
        url-pattern: /v1/auth/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="auth">
                      <Appenders>
                        <Console name="console" target="SYSTEM_OUT">
                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                        </Console>
                        <Socket name="logstash" host="d40c24bf-5206-4b4c-ba70-3275167a6e4b-ls.logit.io" port="17698" protocol="tcp">
                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                        </Socket>
                      </Appenders>
                      <Loggers>
                        <!-- Resources (REST) -->
                        <Logger name="com.fri.rso.fririders.auth.resource.AuthResource" level="trace" additivity="false">
                          <AppenderRef ref="console"/>
                          <AppenderRef ref="logstash"/>
                        </Logger>
                        <!-- Default logger -->
                        <Root level="all">
                          <AppenderRef ref="console" level="info"/>
                          <AppenderRef ref="console" level="trace"/>
                          <AppenderRef ref="logstash" level="trace"/>
                          <AppenderRef ref="logstash" level="info"/>
                        </Root>
                      </Loggers>
                  </Configuration>'
  fault-tolerance:
    config:
      watch-enabled: true
      watch-properties: timeout.value,circuit-breaker.failure-ratio,bulkhead.value
    auth:
      bulkhead:
        value: 5


auth-config:
  healthy: true
